Repository bmresearch/Solnet, pull requests merged in 2021-06, with the labels that each got.

#26 Implementation of slotSubscribe.
  src/Solnet.Rpc/Messages/JsonRpcRequest.cs
  src/Solnet.Rpc/Messages/JsonRpcStreamResponse.cs
  src/Solnet.Rpc/SolanaStreamingRpcClient.cs
  test/Solnet.Rpc.Test/Resources/SlotSubscribe.json
  test/Solnet.Rpc.Test/Resources/SlotSubscribeNotification.json
  test/Solnet.Rpc.Test/SolanaStreamingClientTest.cs
  test/Solnet.Rpc.Test/Solnet.Rpc.Test.csproj
Labels: enhancement

#25 Add tests for the RPC client
  README.md
  src/Solnet.Examples/TransactionBuilderExample.cs
  src/Solnet.Rpc/Core/Http/JsonRpcClient.cs
  src/Solnet.Rpc/Messages/JsonRpcResponse.cs
  src/Solnet.Rpc/Models/ErrorResult.cs
  src/Solnet.Rpc/Models/InstructionErrorJsonConverter.cs
  src/Solnet.Rpc/Models/Logs.cs
  src/Solnet.Rpc/SolanaRpcClient.cs
  src/Solnet.Rpc/Utilities/AddressExtensions.cs
  src/Solnet.Rpc/Utilities/Ed25519Extensions.cs
  test/Solnet.Rpc.Test/Resources/Http/EmptyPayloadRequest.json
  test/Solnet.Rpc.Test/Resources/Http/EmptyPayloadResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetAccountInfoRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetAccountInfoResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetBalanceRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetBalanceResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetBlockCommitmentRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetBlockCommitmentResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetBlockTimeRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetBlockTimeResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetClusterNodesRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetClusterNodesResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetGenesisHashRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetGenesisHashResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetMinimumLedgerSlotRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetMinimumLedgerSlotResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetRecentBlockhashRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetRecentBlockhashResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetSupplyRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetSupplyResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountBalanceRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountBalanceResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountsByDelegateRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountsByDelegateResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountsByOwnerRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenAccountsByOwnerResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenLargestAccountsRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenLargestAccountsResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenSupplyRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTokenSupplyResponse.json
  test/Solnet.Rpc.Test/Resources/Http/GetTransactionCountRequest.json
  test/Solnet.Rpc.Test/Resources/Http/GetTransactionCountResponse.json
  test/Solnet.Rpc.Test/Resources/Http/SendTransactionRequest.json
  test/Solnet.Rpc.Test/Resources/Http/SendTransactionResponse.json
  test/Solnet.Rpc.Test/Resources/Http/SimulateTransactionInsufficientLamportsRequest.json
  test/Solnet.Rpc.Test/Resources/Http/SimulateTransactionInsufficientLamportsResponse.json
  test/Solnet.Rpc.Test/Resources/Http/SimulateTransactionRequest.json
  test/Solnet.Rpc.Test/Resources/Http/SimulateTransactionResponse.json
  test/Solnet.Rpc.Test/SolanaRpcClientTest.cs
  test/Solnet.Rpc.Test/SolanaStreamingClientTest.cs
  test/Solnet.Rpc.Test/Solnet.Rpc.Test.csproj
  test/Solnet.Rpc.Test/UtilitiesTest.cs
Labels: documentation, enhancement

#72 Fixed memory leak.
  SharedBuildProperties.props
  src/Solnet.Rpc/Core/Http/JsonRpcClient.cs
Labels: bug
